services:
  vulnerable-app:
    build: ./vulnerable-app
    container_name: vulnerable_app
    ports:
      - "8080:8080"
    environment:
      - PAYLOAD_SERVER_URL=http://payload-server:8000
    depends_on:
      - payload-server
      - ldap-server
    networks:
      - log4shell-network

  payload-server:
    build: ./payload-server
    container_name: payload_server
    ports:
      - "8000:8000"
    networks:
      - log4shell-network

  ldap-server:
    build: ./ldap-server
    container_name: ldap_server
    ports:
      - "1389:1389"
    environment:
      - PAYLOAD_SERVER_URL=http://payload-server:8000
    networks:
      - log4shell-network

networks:
  log4shell-network:
    name: log4shell-network
    driver: bridge
